project_id = "aeiypruqgzqauvyftitw"

[functions.barcode-lookup]
verify_jwt = false

[functions.calculate-risk-scores]
verify_jwt = false

[functions.evaluate-auto-messages]
verify_jwt = false

[functions.progress-insights]
verify_jwt = false

[functions.estimate-body-fat]
verify_jwt = false
