
-- Weekly calorie suggestions (coach-only, generated by TDEE engine)
CREATE TABLE public.weekly_calorie_suggestions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  client_id UUID NOT NULL,
  coach_id UUID,
  estimated_tdee NUMERIC NOT NULL,
  current_calories INTEGER NOT NULL,
  suggested_calories INTEGER NOT NULL,
  suggested_protein INTEGER,
  suggested_carbs INTEGER,
  suggested_fat INTEGER,
  phase TEXT NOT NULL DEFAULT 'cut',
  reason TEXT NOT NULL,
  metabolic_adaptation_pct NUMERIC DEFAULT 0,
  predicted_weekly_change NUMERIC DEFAULT 0,
  predicted_4week_weight NUMERIC,
  biofeedback_factors JSONB DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending',
  coach_notes TEXT,
  coach_modified_calories INTEGER,
  resolved_at TIMESTAMPTZ,
  week_start DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.weekly_calorie_suggestions ENABLE ROW LEVEL SECURITY;

-- Only coaches see suggestions
CREATE POLICY "Coaches can manage suggestions"
ON public.weekly_calorie_suggestions FOR ALL
USING (has_role(auth.uid(), 'coach') OR has_role(auth.uid(), 'admin'))
WITH CHECK (has_role(auth.uid(), 'coach') OR has_role(auth.uid(), 'admin'));

-- Add reverse_diet to client_goals phase options and add aggressiveness
ALTER TABLE public.client_goals 
ADD COLUMN IF NOT EXISTS aggressiveness NUMERIC DEFAULT 0.5,
ADD COLUMN IF NOT EXISTS phase_notes TEXT;

-- Add biofeedback columns to tdee_estimates
ALTER TABLE public.tdee_estimates
ADD COLUMN IF NOT EXISTS avg_steps INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS avg_sleep_hours NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cardio_minutes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS training_sessions INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS metabolic_adaptation_pct NUMERIC DEFAULT 0;
