
-- Seed common exercises
INSERT INTO public.exercises (name, category, created_by) VALUES
('Barbell Back Squat', 'Lower Body', NULL),
('Bench Press', 'Upper Body', NULL),
('Deadlift', 'Full Body', NULL),
('Leg Press', 'Lower Body', NULL),
('Leg Curl', 'Lower Body', NULL),
('Leg Extension', 'Lower Body', NULL),
('Barbell Row', 'Back', NULL),
('Lat Pulldown', 'Back', NULL),
('Incline Dumbbell Press', 'Chest', NULL),
('Dumbbell Flyes', 'Chest', NULL),
('Dumbbell Rows', 'Back', NULL),
('Cable Chest Flyes', 'Chest', NULL),
('Overhead Press', 'Shoulders', NULL),
('Lateral Raise', 'Shoulders', NULL),
('Barbell Curl', 'Arms', NULL),
('Tricep Rope Pushdown', 'Arms', NULL),
('Dumbbell Curl', 'Arms', NULL),
('Overhead Tricep Extension', 'Arms', NULL),
('Pull-ups', 'Back', NULL),
('Dips', 'Chest/Triceps', NULL),
('Machine Chest Press', 'Chest', NULL),
('Pec Deck', 'Chest', NULL),
('Seated Shoulder Press', 'Shoulders', NULL),
('Shrugs', 'Shoulders', NULL),
('Calf Raises', 'Lower Body', NULL),
('Romanian Deadlift', 'Lower Body', NULL),
('Hack Squat', 'Lower Body', NULL),
('Smith Machine Squat', 'Lower Body', NULL),
('Cable Crossover', 'Chest', NULL),
('Dumbbell Bench Press', 'Chest', NULL)
ON CONFLICT DO NOTHING;
